baseURL: "https://Kazuma0417.github.io/portfolio/"
canonifyurls: false
publishDir: "content"
title: Kazuma
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  #    env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kazuma
  description: "Blog of Kazuma, a software engineer."
  keywords: [Blog, Portfolio, PaperMod]
  author: Kazuma Oshiro
  # author: ["Me", "You"] # multiple authors
  images: ["profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "Thinking_Face_Emoji_large.png"
    favicon16x16: "Thinking_Face_Emoji_large.png"
    favicon32x32: "Thinking_Face_Emoji_large.png"
    apple_touch_icon: "Thinking_Face_Emoji_large.png"
    safari_pinned_tab: "Thinking_Face_Emoji_large.png"

  label:
    text: "🏠 Home"
    # icon: Thinking_Face_Emoji_large.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Kazuma"
    subtitle: "a software engineer."
    #imageUrl: "profile.jpg"
    imageUrl: "profile.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    # buttons:
    #     - name: Posts
    #       url: posts

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/Kazuma0417"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: post
      weight: 5
    - identifier: profile
      name: profile
      url: profile
      weight: 10
    - name: works
      url: works
      weight: 15
    - identifier: tags
      name: tags
      url: tags/
      weight: 25
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai